version: "3.9"  # you can remove or leave; Docker ignores it

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env

  backend:
    build: ./backend
    container_name: demandradar-backend
    ports:
      - "${BACKEND_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: demandradar-frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - backend
