version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: demandradar-backend
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: "mongodb://mongodb:27017/"
    volumes:
      - ./backend/static:/app/static

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: demandradar-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"  # maps host port 3000 to container's Nginx port 80

volumes:
  mongo_data:
