version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: demandradar-backend
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: "mongodb://mongodb:27017/demandradar"
      NODE_ENV: "development"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/static:/app/static

  frontend:
    build:
      context: ./frontend
    container_name: demandradar-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:8000

volumes:
  mongo_data:
